on:
  # Triggered every 10min or manually
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  append:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: node append.mjs >> log.json
      - run: node append2.mjs >> log_latest_tx.json
      - name: Push
        run: |
          git config --global user.name 'automated'
          git config --global user.email 'automated@users.noreply.github.com'
          git diff --exit-code || git commit -am "Automated" && git push
